const router = [
  {
    path: '/user',
    layout: false,
    routes: [
      {
        path: '/user/login',
        layout: false,
        name: 'login',
        component: './user/Login',
      },
      {
        path: '/user',
        redirect: '/user/login',
      },
      {
        name: 'register-result',
        icon: 'smile',
        path: '/user/register-result',
        component: './user/register-result',
      },
      {
        name: 'register',
        icon: 'smile',
        path: '/user/register',
        component: './user/register',
      },
      {
        component: '404',
      },
    ],
  },
  // {
  //   path: '/dashboard',
  //   name: 'dashboard',
  //   icon: 'dashboard',
  //   routes: [
  //     {
  //       path: '/dashboard',
  //       redirect: '/dashboard/analysis',
  //     },
  //     {
  //       name: 'analysis',
  //       icon: 'smile',
  //       path: '/dashboard/analysis',
  //       component: './dashboard/analysis',
  //     },
  //     {
  //       name: 'monitor',
  //       icon: 'smile',
  //       path: '/dashboard/monitor',
  //       component: './dashboard/monitor',
  //     },
  //     {
  //       name: 'workplace',
  //       icon: 'smile',
  //       path: '/dashboard/workplace',
  //       component: './dashboard/workplace',
  //     },
  //   ],
  // },
  // {
  //   path: '/form',
  //   icon: 'form',
  //   name: 'form',
  //   routes: [
  //     {
  //       path: '/form',
  //       redirect: '/form/basic-form',
  //     },
  //     {
  //       name: 'basic-form',
  //       icon: 'smile',
  //       path: '/form/basic-form',
  //       component: './form/basic-form',
  //     },
  //     {
  //       name: 'step-form',
  //       icon: 'smile',
  //       path: '/form/step-form',
  //       component: './form/step-form',
  //     },
  //     {
  //       name: 'advanced-form',
  //       icon: 'smile',
  //       path: '/form/advanced-form',
  //       component: './form/advanced-form',
  //     },
  //   ],
  // },
  // {
  //   path: '/list',
  //   icon: 'table',
  //   name: 'list',
  //   routes: [
  //     {
  //       path: '/list/search',
  //       name: 'search-list',
  //       component: './list/search',
  //       routes: [
  //         {
  //           path: '/list/search',
  //           redirect: '/list/search/articles',
  //         },
  //         {
  //           name: 'articles',
  //           icon: 'smile',
  //           path: '/list/search/articles',
  //           component: './list/search/articles',
  //         },
  //         {
  //           name: 'projects',
  //           icon: 'smile',
  //           path: '/list/search/projects',
  //           component: './list/search/projects',
  //         },
  //         {
  //           name: 'applications',
  //           icon: 'smile',
  //           path: '/list/search/applications',
  //           component: './list/search/applications',
  //         },
  //       ],
  //     },
  //     {
  //       path: '/list',
  //       redirect: '/list/table-list',
  //     },
  //     {
  //       name: 'table-list',
  //       icon: 'smile',
  //       path: '/list/table-list',
  //       component: './list/table-list',
  //     },
  //     {
  //       name: 'basic-list',
  //       icon: 'smile',
  //       path: '/list/basic-list',
  //       component: './list/basic-list',
  //     },
  //     {
  //       name: 'card-list',
  //       icon: 'smile',
  //       path: '/list/card-list',
  //       component: './list/card-list',
  //     },
  //   ],
  // },
  // {
  //   path: '/profile',
  //   name: 'profile',
  //   icon: 'profile',
  //   routes: [
  //     {
  //       path: '/profile',
  //       redirect: '/profile/basic',
  //     },
  //     {
  //       name: 'basic',
  //       icon: 'smile',
  //       path: '/profile/basic',
  //       component: './profile/basic',
  //     },
  //     {
  //       name: 'advanced',
  //       icon: 'smile',
  //       path: '/profile/advanced',
  //       component: './profile/advanced',
  //     },
  //   ],
  // },
  // {
  //   name: 'result',
  //   icon: 'CheckCircleOutlined',
  //   path: '/result',
  //   routes: [
  //     {
  //       path: '/result',
  //       redirect: '/result/success',
  //     },
  //     {
  //       name: 'success',
  //       icon: 'smile',
  //       path: '/result/success',
  //       component: './result/success',
  //     },
  //     {
  //       name: 'fail',
  //       icon: 'smile',
  //       path: '/result/fail',
  //       component: './result/fail',
  //     },
  //   ],
  // },
  // {
  //   name: 'exception',
  //   icon: 'warning',
  //   path: '/exception',
  //   routes: [
  //     {
  //       path: '/exception',
  //       redirect: '/exception/403',
  //     },
  //     {
  //       name: '403',
  //       icon: 'smile',
  //       path: '/exception/403',
  //       component: './exception/403',
  //     },
  //     {
  //       name: '404',
  //       icon: 'smile',
  //       path: '/exception/404',
  //       component: './exception/404',
  //     },
  //     {
  //       name: '500',
  //       icon: 'smile',
  //       path: '/exception/500',
  //       component: './exception/500',
  //     },
  //   ],
  // },
  // {
  //   name: 'account',
  //   icon: 'user',
  //   path: '/account',
  //   routes: [
  //     {
  //       path: '/account',
  //       redirect: '/account/center',
  //     },
  //     {
  //       name: 'center',
  //       icon: 'smile',
  //       path: '/account/center',
  //       component: './account/center',
  //     },
  //     {
  //       name: 'settings',
  //       icon: 'smile',
  //       path: '/account/settings',
  //       component: './account/settings',
  //     },
  //   ],
  // },
  // {
  //   name: 'editor',
  //   icon: 'highlight',
  //   path: '/editor',
  //   routes: [
  //     {
  //       path: '/editor',
  //       redirect: '/editor/flow',
  //     },
  //     {
  //       name: 'flow',
  //       icon: 'smile',
  //       path: '/editor/flow',
  //       component: './editor/flow',
  //     },
  //     {
  //       name: 'mind',
  //       icon: 'smile',
  //       path: '/editor/mind',
  //       component: './editor/mind',
  //     },
  //     {
  //       name: 'koni',
  //       icon: 'smile',
  //       path: '/editor/koni',
  //       component: './editor/koni',
  //     },
  //   ],
  // },
  // {
  //   name: '模板',
  //   icon: 'user',
  //   path: '/template',
  //   routes: [
  //     {
  //       path: '/template',
  //       redirect: '/template/useModal',
  //     },
  //     {
  //       name: '弹框模板',
  //       icon: 'smile',
  //       path: '/template/useModal',
  //       component: './template/useModal',
  //     },
  //     {
  //       name: '流程配置页模板',
  //       icon: 'smile',
  //       path: '/template/useFlow/useFlowDemo',
  //       component: './template/useFlow/useFlowDemo',
  //     },
  //     {
  //       name: '客户选择带弹窗',
  //       icon: 'smile',
  //       path: '/template/customerBtn/customerBtnDemo',
  //       component: './template/customerBtn/customerBtnDemo',
  //     },
  // {
  //   name: 'settings',
  //   icon: 'smile',
  //   path: '/account/settings',
  //   component: './account/settings',
  // },
  // {
  //   name: '树形结构',
  //   icon: 'smile',
  //   path: '/template/tree',
  //   component: './template/tree',
  // },
  //     {
  //       name: 'select',
  //       icon: 'smile',
  //       path: '/template/select',
  //       component: './template/select',
  //     },
  //     {
  //       name: '分步提交',
  //       icon: 'smile',
  //       path: '/template/steps',
  //       component: './template/steps',
  //     },
  //     {
  //       name: '审批模板',
  //       icon: 'smile',
  //       path: '/template/approve',
  //       component: './template/approve',
  //     },
  //     {
  //       name: '高级表单',
  //       icon: 'smile',
  //       path: '/template/form',
  //       component: './template/advanced-form',
  //     },
  //     {
  //       name: '基础表单',
  //       icon: 'smile',
  //       path: '/template/basic',
  //       component: './template/basic',
  //     },
  //     {
  //       name: '查看附件弹框',
  //       icon: 'smile',
  //       path: '/template/viewAtt',
  //       component: './template/viewAtt',
  //     },
  // ],
  // },
  {
    name: '系统管理(+)',
    icon: 'setting',
    path: '/system',
    routes: [
      {
        name: '用户管理',
        icon: 'smile',
        path: '/system/user',
        component: './system/user',
      },
      {
        name: '新增用户',
        icon: 'smile',
        path: '/system/user/add',
        component: './system/user/add',
        hideInMenu: true,
      },
      {
        name: '编辑用户',
        icon: 'smile',
        path: '/system/user/edit/:id?',
        component: './system/user/edit',
        hideInMenu: true,
      },
      {
        name: '角色管理',
        icon: 'smile',
        path: '/system/role',
        component: './system/role',
      },
      {
        name: '菜单管理',
        icon: 'smile',
        path: '/system/menu',
        component: './system/menu',
      },
      {
        name: '登录日志',
        icon: 'smile',
        path: '/system/log',
        component: './system/log',
      },
      {
        name: '操作日志',
        icon: 'smile',
        path: '/system/operation',
        component: './system/operation',
      },
      {
        name: 'banner管理',
        icon: 'smile',
        path: '/system/banner',
        component: './system/banner',
      },
    ],
  },
  {
    name: '学校管理',
    icon: 'BankOutlined',
    path: '/school',
    routes: [
      {
        path: '/school',
        redirect: '/school/School',
      },
      {
        name: '学校管理',
        icon: 'smile',
        path: '/school/School',
        routes: [
          {
            path: '/school/School',
            redirect: '/school/School/index',
          },
          {
            name: '学校管理',
            icon: 'smile',
            path: '/school/School/index',
            component: './school/School',
            hideInMenu: true,
          },
          {
            name: '新增学校',
            icon: 'smile',
            path: '/school/School/add',
            component: './school/School/add',
            hideInMenu: true,
          },
          {
            name: '编辑学校',
            icon: 'smile',
            path: '/school/School/edit/:id?',
            component: './school/School/edit',
            hideInMenu: true,
          },
        ],
      },
      {
        name: '专业管理',
        icon: 'smile',
        path: '/school/major',
        component: './school/major',
      },
      {
        name: '学科管理',
        icon: 'smile',
        path: '/school/subjectAdmin',
        component: './school/subjectAdmin',
      },
      {
        name: '年级管理',
        icon: 'smile',
        path: '/school/grade',
        component: './school/grade',
      },
      {
        name: '班级管理',
        icon: 'smile',
        path: '/school/class',
        component: './school/class',
      },
      {
        name: '教师管理',
        icon: 'smile',
        path: '/school/classroom',
        component: './school/classroom',
      },
      {
        name: '新增教师',
        icon: 'smile',
        path: '/school/classroom/add',
        component: './school/classroom/add',
        hideInMenu: true,
      },
      {
        name: '编辑教师信息',
        icon: 'smile',
        path: '/school/classroom/edit/:id?',
        component: './school/classroom/edit',
        hideInMenu: true,
      },
      {
        name: '学生管理',
        icon: 'smile',
        path: '/school/student',
        component: './school/student',
      },
      {
        name: '新增',
        icon: 'smile',
        path: '/school/student/add',
        component: './school/student/add',
        hideInMenu: true,
      },
      {
        name: '编辑',
        icon: 'smile',
        path: '/school/student/edit/:id?',
        component: './school/student/edit',
        hideInMenu: true,
      },
      {
        name: '范例',
        icon: 'smile',
        path: '/school/student/example',
        component: './school/student/example',
        hideInMenu: true,
      },
    ],
  },
  {
    name: '教务管理',
    icon: 'BookOutlined',
    path: '/educational',
    routes: [
      {
        path: '/educational',
        redirect: '/educational/knowledge',
      },
      {
        name: '知识点管理',
        icon: 'smile',
        path: '/educational/knowledge',
        component: './educational/knowledge',
      },
      {
        name: '教材管理',
        icon: 'smile',
        path: '/educational/teaching',
        component: './educational/teaching',
      },
      {
        name: '章节管理',
        icon: 'smile',
        path: '/educational/teaching/chapter/:id?/:name?',
        component: './educational/teaching/chapter',
        hideInMenu: true,
      },
      {
        name: '线下考试',
        icon: 'smile',
        path: '/educational/offline',
        component: './educational/offline',
      },
      {
        name: '新增',
        icon: 'smile',
        path: '/educational/offline/add',
        component: './educational/offline/add',
        hideInMenu: true,
      },
      {
        name: '修改',
        icon: 'smile',
        path: '/educational/offline/edit/:id?',
        component: './educational/offline/edit',
        hideInMenu: true,
      },
      {
        name: '成绩',
        icon: 'smile',
        path: '/educational/offline/achievement/:id?',
        component: './educational/offline/achievement',
        hideInMenu: true,
      },
      {
        name: '查看',
        icon: 'smile',
        path: '/educational/offline/see/:id?',
        component: './educational/offline/see',
        hideInMenu: true,
      },
      {
        name: '组卷模拟管理',
        icon: 'smile',
        path: '/educational/template',
        component: './educational/template',
      },
      {
        name: '新增模板',
        icon: 'smile',
        path: '/educational/template/add',
        component: './educational/template/add',
        hideInMenu: true,
      },
      {
        name: '编辑模板',
        icon: 'smile',
        path: '/educational/template/edit/:id?',
        component: './educational/template/edit',
        hideInMenu: true,
      },
      {
        name: '设置知识点',
        icon: 'smile',
        path: '/educational/template/set/:id/:tempType',
        component: './educational/template/set',
        hideInMenu: true,
      },
      {
        name: '任务训练',
        icon: 'smile',
        path: '/educational/task',
        component: './educational/task',
      },
      {
        name: '设置题目',
        icon: 'smile',
        path: '/educational/task/set/:id?',
        component: './educational/task/set',
        hideInMenu: true,
      },
      {
        name: '任务训练预览',
        icon: 'smile',
        path: '/educational/task/preview',
        component: './educational/task/preview',
        hideInMenu: true,
      },
      {
        name: '模拟考试',
        icon: 'smile',
        path: '/educational/simulation',
        component: './educational/simulation',
      },
      {
        name: '设置题目',
        icon: 'smile',
        path: '/educational/simulation/set/:id?',
        component: './educational/simulation/set',
        hideInMenu: true,
      },
      {
        name: '模拟考试预览',
        icon: 'smile',
        path: '/educational/simulation/preview',
        component: './educational/simulation/preview',
        hideInMenu: true,
      },
    ],
  },
  {
    name: '题库管理',
    icon: 'DatabaseOutlined',
    path: '/question',
    routes: [
      {
        path: '/question',
        redirect: '/question/subject',
      },
      {
        name: '题目管理',
        icon: 'smile',
        path: '/question/subject',
        component: './question/subject',
      },
      {
        name: '新增',
        icon: 'smile',
        path: '/question/subject/add',
        component: './question/subject/add',
        // hideInMenu: true,
      },
      {
        name: '导入',
        icon: 'smile',
        path: '/question/subject/import',
        component: './question/subject/import',
        hideInMenu: true,
      },
      {
        name: '页面1',
        icon: 'smile',
        path: '/question/subject/page',
        component: './question/subject/page',
        // hideInMenu: true,
      },
      {
        name: '范例',
        icon: 'smile',
        path: '/question/subject/example',
        component: './question/subject/example',
        hideInMenu: true,
      },
    ],
  },
  {
    name: '系统设置',
    icon: 'setting',
    path: '/set',
    routes: [
      {
        path: '/set',
        redirect: '/set/website',
      },
      {
        name: '网站设置',
        icon: 'smile',
        path: '/set/website',
        component: './set/website/index',
      },
      {
        name: '变量设置',
        icon: 'smile',
        path: '/set/variable',
        component: './set/variable/index',
      },
    ],
  },
  {
    name: '类型管理',
    icon: 'HolderOutlined',
    path: '/type',
    routes: [
      {
        path: '/type',
        redirect: '/type/hard',
      },
      {
        name: '难易度',
        icon: 'smile',
        path: '/type/hard',
        component: './type/hard',
      },
      {
        name: '考试类型',
        icon: 'smile',
        path: '/type/test',
        component: './type/test',
      },
      {
        name: '题目类型',
        icon: 'smile',
        path: '/type/subject',
        component: './type/subject',
      },
      {
        name: '作业类型',
        icon: 'smile',
        path: '/type/task',
        component: './type/task',
      },
      {
        name: '学校类型',
        icon: 'smile',
        path: '/type/school',
        component: './type/school',
      },
      {
        name: '任务训练类型',
        icon: 'smile',
        path: '/type/train',
        component: './type/train',
      },
      {
        name: '专业分类',
        icon: 'smile',
        path: '/type/professionalType',
        component: './type/professionalType',
      },
    ],
  },
  // {
  //   path: '/',
  //   // redirect: '/dashboard/analysis',
  //   redirect: '/system/user',
  // },
  {
    component: '404',
  },
];

export default JSON.stringify(router);
