export default defineAppConfig({
  pages: [
    'pages/home/home',
    'pages/login/login',
    'pages/login-phone/login-phone',
    'pages/login-captcha/login-captcha',
    'pages/property/property',
    'pages/property-list/property',
    'pages/order-list/order-list',
    'pages/order-detail/order-detail',
    'pages/privacy-policy/privacy-policy',
    'pages/setup/setup',
    'pages/comment-list/comment-list',
    'pages/account/account',
    'pages/personal/personal',
    'pages/blind-box-detail/blind-box-detail',
    'pages/official-goods-detail/official-goods-detail',
    'pages/place-order/place-order',
    'pages/pay-success/pay-success',
    'pages/paid-middle/paid-middle',
    'pages/pay/pay',
    'pages/article/article',
    'pages/web-viewer/web-viewer',
    /*合成中心*/ 'pages/combind-center/index',
    /*合成大挑战*/ 'pages/combind-detail/index',
    /*合成藏品详情*/ 'pages/nft-detail/index',
    /*发行方详情*/ 'pages/issuer/index',
    /*藏品详情*/ 'pages/collection/index',
    /*操作密码*/ 'pages/pin/index',
    /*操作密码确认*/ 'pages/pin-confirm/index',
    /*操作密码成功*/ 'pages/pin-success/index',
    /*藏品转赠*/ 'pages/nft-gift/index',
    /*收货地址管理*/ 'pages/delivery-address-list/index',
    /*新增收货地址*/ 'pages/delivery-address/index',
    /*兑换详情*/ 'pages/exchange-detail/index',
    /*兑换页面*/ 'pages/exchange/index',
    /*物流页面*/ 'pages/logistics/index',
    /*邀请码*/ 'pages/invitation/index',
    /*专区*/ 'pages/zone/index',
    /*超际授权页面*/ 'pages/third-auth/index',
    /*发现页面*/ 'pages/discover/discover',
    /*分享状态*/ 'pages/share-status/index',
    /*我的收藏*/ 'pages/my-collect/index',
    /*我的分享*/ 'pages/my-share/index',
    /*发布分享*/ 'pages/share-publish/index',
    /**查看用户,用户分享*/'pages/user-page/index',
    /**钱包地址*/ 'pages/wallet-page/index',
    /**实物流转发售*/ 'pages/flow-sale-publish/index',
    /**发现详情页面*/ 'pages/discover-detail/index',
    /**售卖管理页面*/ 'pages/my-flow-sale/index'
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: '鸭藏',
    navigationBarTextStyle: 'black',
  },
  disableSwipeBack: true,
  useExtendedLib: {
    weui: true,
  },
  tabBar: {
    selectedColor: '#3439FF',
    color: '#777',
    list: [],
  },
  subpackages: [],
})
